export const EventDetails = [
    {
        id: 1,
        name: "Cloud Innovation Summit",
        date: "2024-10-15",
        speaker: "Jane Doe",
        Status: "in-progress",
    },
    {
        id: 2,
        name: "Blockchain Revolution Conference",
        date: "2024-11-05",
        speaker: "Dr.Peter Smith",
        Status: "in-progress",
    },
    {
        id: 3,
        name: "AI in Healthcare Symposium",
        date: "2024-12-01",
        speaker: "Dr. Aisha Malik",
        Status: "completed",
    },
    {
        id: 4,
        name: "Future of Fintech Forum",
        date: "2024-10-25",
        speaker: "John Lee",
        Status: "completed",
    },
    {
        id: 5,
        name: "Data Analytics in Business",
        date: "2024-11-12",
        speaker: "Rachel Moore",
        Status: "completed",
    },
    {
        id: 6,
        name: "Sustainable Energy Expo",
        date: "2024-09-28",
        speaker: "Prof. Alan Green",
        Status: "completed",
    },
    {
        id: 7,
        name: "Web3 Interfaces Workshop",
        date: "2024-10-10",
        speaker: "Kevin Adams",
        Status: "in-progress",
    },
    {
        id: 8,
        name: "Cybersecurity for Startups",
        date: "2024-11-19",
        speaker: "Emily Zhang",
        Status: "completed",
    },
];
